apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-gitlab-sourcegraph
  namespace: prod
  labels:
    app: gitlab-sourcegraph
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50G