apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: devops-infra
spec:
  selector:
    matchLabels:
      app: kafka-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "4Gi"
              cpu: "4000m"
            limits:
              memory: "8Gi"
              cpu: "6000m"
          env:
            - name: TZ
              value: Europe/Kiev
            - name: KAFKA_CLUSTERS_0_NAME
              value: dev
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: example.com:31092   
