apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: devops-infra
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30400

  selector:
    app: kafka-ui
