apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-nifi-azure-backup
  namespace: prod
  labels:
    app: nifi-azure-backup
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500G