apiVersion: v1
kind: Service
metadata:
  name: sdw3
  namespace: devops-infra-beta
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: segment1
      port: 6000
      targetPort: 6000
    - name: segment2
      port: 6001
      targetPort: 6001
    - name: segment3
      port: 6002
      targetPort: 6002
    - name: segment4
      port: 6003
      targetPort: 6003
    - name: segment5
      port: 6004
      targetPort: 6004
    - name: segment6
      port: 6005
      targetPort: 6005
  selector:
    app: sdw3
