apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-greenplum-mdw
  namespace: devops-infra-beta
  labels:
    app: mdw
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300G