apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-greenplum-sdw5
  namespace: devops-infra-beta
  labels:
    app: sdw5
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300G