kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-test
  namespace: dev
spec:
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
        - name: postgres-test
          image: postgres:14.1
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-volume
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: postgres-test