apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-test
  namespace: dev
  labels:
    app: postgres-test
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi