apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 5432
      name: db-port
      nodePort: 31000
      protocol: TCP
  selector:
    app: postgres-test